# Generated by Django 5.2.11 on 2026-02-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='skill',
            name='course_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='skill',
            name='price_type',
            field=models.CharField(default='Free', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='skill',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='skill_thumbnails/'),
        ),
    ]
