# Generated by Django 5.2.10 on 2026-02-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_skill_category_skill_course_link_skill_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
